In [1]:
from mxnet import nd

In [3]:
x=nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [6]:
x.shape

(12,)

In [7]:
x=x.reshape((3,4))
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [8]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [15]:
X=nd.ones((3,4))

In [13]:
Y=nd.array([[1,2,3,4],[2,1,3,4],[3,1,2,4]])

In [12]:
nd.random.normal(0,1,shape=(3,4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

In [16]:
X+Y


[[2. 3. 4. 5.]
 [3. 2. 4. 5.]
 [4. 2. 3. 5.]]
<NDArray 3x4 @cpu(0)>

In [17]:
X*Y


[[1. 2. 3. 4.]
 [2. 1. 3. 4.]
 [3. 1. 2. 4.]]
<NDArray 3x4 @cpu(0)>

In [18]:
X/Y


[[1.         0.5        0.33333334 0.25      ]
 [0.5        1.         0.33333334 0.25      ]
 [0.33333334 1.         0.5        0.25      ]]
<NDArray 3x4 @cpu(0)>

In [19]:
Y.exp()


[[ 2.7182817  7.389056  20.085537  54.59815  ]
 [ 7.389056   2.7182817 20.085537  54.59815  ]
 [20.085537   2.7182817  7.389056  54.59815  ]]
<NDArray 3x4 @cpu(0)>

In [20]:
nd.dot(X,Y.T)


[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
<NDArray 3x3 @cpu(0)>

In [21]:
nd.concat(X,Y,dim=0),nd.concat(X,Y,dim=1)

(
 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 2. 3. 4.]
  [2. 1. 3. 4.]
  [3. 1. 2. 4.]]
 <NDArray 6x4 @cpu(0)>, 
 [[1. 1. 1. 1. 1. 2. 3. 4.]
  [1. 1. 1. 1. 2. 1. 3. 4.]
  [1. 1. 1. 1. 3. 1. 2. 4.]]
 <NDArray 3x8 @cpu(0)>)

In [22]:
X==Y


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [23]:
X.sum()


[12.]
<NDArray 1 @cpu(0)>

In [24]:
X.norm().asscalar()

3.4641016

In [26]:
A=nd.arange(3).reshape((3,1))
B=nd.arange(2).reshape((1,2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [27]:
A+B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [28]:
Y[1:3]


[[2. 1. 3. 4.]
 [3. 1. 2. 4.]]
<NDArray 2x4 @cpu(0)>

In [29]:
Y[2,3]


[4.]
<NDArray 1 @cpu(0)>

In [30]:
Y[1:3,2]


[3. 2.]
<NDArray 2 @cpu(0)>

In [31]:
before=id(Y)
Y=Y+X
id(Y)==before

False

In [32]:
Z=Y.zeros_like()
before=id(Z)
Z[:]=X+Y
id(Z)==before

True

In [33]:
nd.elemwise_add(X,Y,out=Z)
id(Z)==before

True

In [35]:
import numpy as np
P=np.ones((2,3))
D=nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [36]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [37]:
X<Y


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [39]:
X>Y


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [40]:
from mxnet import autograd

In [50]:
x=nd.arange(4).reshape((4,1))

In [51]:
x.attach_grad() #申请存储梯度所需要的内存
with autograd.record():
    y=2*nd.dot(x.T,x)
y


[[28.]]
<NDArray 1x1 @cpu(0)>

In [52]:
y.backward()
y


[[28.]]
<NDArray 1x1 @cpu(0)>

In [54]:
assert(x.grad-4*x).norm().asscalar()==0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [56]:
def f(a):
    b=a*2
    while b.norm().asscalar()<1000:
        b=b*2
    if b.sum().asscalar()>0:
        c=b
    else:
        c=100*b
    return c

In [57]:
a=nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
    c=f(a)
c.backward()
a.grad==c/a


[1.]
<NDArray 1 @cpu(0)>

In [61]:
a=nd.arange(4).reshape((4,1))
a.norm().asscalar()

3.7416573

In [72]:
def f(x):
    y=nd.ones((1,1))
    for i in range(2):
       y=y*x
    return y
a=nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
    y=f(a)
y.backward()
print(2*a,a.grad)
# print(4*pow(a.grad,4))


[0.10767588]
<NDArray 1 @cpu(0)> 
[0.10767588]
<NDArray 1 @cpu(0)>
